# Generated by Django 5.0.4 on 2024-06-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('interested_in', models.CharField(max_length=10)),
                ('interests', models.TextField()),
                ('bio', models.TextField()),
            ],
        ),
    ]
