# Generated by Django 5.0.6 on 2024-06-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0003_alter_utilisateur_centre_interet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('centres_d_interet', models.TextField(blank=True)),
                ('photo', models.URLField(blank=True)),
                ('presentation', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
