# Generated by Django 5.0.6 on 2024-06-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0004_userprofile_delete_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='prenom',
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(condition=models.Q(('password__icontains', 'example')), fields=['password'], name='partial_password_index'),
        ),
    ]
