# Generated by Django 5.0.6 on 2024-06-17 12:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0006_remove_userprofile_partial_password_index_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(choices=[(18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60)])),
                ('genre', models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme')], max_length=10)),
                ('photo_profil', models.ImageField(upload_to='img/')),
                ('centres_interets', models.CharField(choices=[('football', 'Football'), ('basketball', 'BasketBall'), ('tennis', 'Tennis'), ('voyage', 'Voyage'), ('nature', 'Nature'), ('musique', 'Musique'), ('films', 'Films et Series TV'), ('lecture', 'Lecture'), ('footing', 'Footing'), ('cuisine', 'Cuisine'), ('jeux_videos', 'Jeux Vidéos'), ('jeux_societe', 'Jeux de Sociétés'), ('arts', 'Arts et Créations'), ('blagues', 'Blagues'), ('sexto', 'Sextos')], max_length=20)),
                ('description', models.TextField()),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('presentation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddIndex(
            model_name='profil',
            index=models.Index(fields=['email'], name='email_index'),
        ),
    ]
