# Generated by Django 5.0.6 on 2024-06-20 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GO', '0008_remove_profil_password_profil_friends_profil_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
